package asm

type DADD struct{ NoOperandsInstruction }
type FADD struct{ NoOperandsInstruction }
type IADD struct{ NoOperandsInstruction }
type LADD struct{ NoOperandsInstruction }
type ALOAD struct{ Index8Instruction }
type ALOAD_0 struct{ NoOperandsInstruction }
type ALOAD_1 struct{ NoOperandsInstruction }
type ALOAD_2 struct{ NoOperandsInstruction }
type ALOAD_3 struct{ NoOperandsInstruction }
type IAND struct{ NoOperandsInstruction }
type LAND struct{ NoOperandsInstruction }
type ANEW_ARRAY struct{ Index16Instruction }
type ARRAY_LENGTH struct{ NoOperandsInstruction }
type ASTORE struct{ Index8Instruction }
type ASTORE_0 struct{ NoOperandsInstruction }
type ASTORE_1 struct{ NoOperandsInstruction }
type ASTORE_2 struct{ NoOperandsInstruction }
type ASTORE_3 struct{ NoOperandsInstruction }
type ATHROW struct{ NoOperandsInstruction }
type CHECK_CAST struct{ Index16Instruction }
type ACONST_NULL struct{ NoOperandsInstruction }
type DCONST_0 struct{ NoOperandsInstruction }
type DCONST_1 struct{ NoOperandsInstruction }
type FCONST_0 struct{ NoOperandsInstruction }
type FCONST_1 struct{ NoOperandsInstruction }
type FCONST_2 struct{ NoOperandsInstruction }
type ICONST_M1 struct{ NoOperandsInstruction }
type ICONST_0 struct{ NoOperandsInstruction }
type ICONST_1 struct{ NoOperandsInstruction }
type ICONST_2 struct{ NoOperandsInstruction }
type ICONST_3 struct{ NoOperandsInstruction }
type ICONST_4 struct{ NoOperandsInstruction }
type ICONST_5 struct{ NoOperandsInstruction }
type LCONST_0 struct{ NoOperandsInstruction }
type LCONST_1 struct{ NoOperandsInstruction }
type D2F struct{ NoOperandsInstruction }
type D2I struct{ NoOperandsInstruction }
type D2L struct{ NoOperandsInstruction }
type DCMPG struct{ NoOperandsInstruction }
type DCMPL struct{ NoOperandsInstruction }
type DDIV struct{ NoOperandsInstruction }
type FDIV struct{ NoOperandsInstruction }
type IDIV struct{ NoOperandsInstruction }
type LDIV struct{ NoOperandsInstruction }
type DLOAD struct{ Index8Instruction }
type DLOAD_0 struct{ NoOperandsInstruction }
type DLOAD_1 struct{ NoOperandsInstruction }
type DLOAD_2 struct{ NoOperandsInstruction }
type DLOAD_3 struct{ NoOperandsInstruction }
type DSTORE struct{ Index8Instruction }
type DSTORE_0 struct{ NoOperandsInstruction }
type DSTORE_1 struct{ NoOperandsInstruction }
type DSTORE_2 struct{ NoOperandsInstruction }
type DSTORE_3 struct{ NoOperandsInstruction }
type DUP struct{ NoOperandsInstruction }
type DUP_X1 struct{ NoOperandsInstruction }
type DUP_X2 struct{ NoOperandsInstruction }
type DUP2 struct{ NoOperandsInstruction }
type DUP2_X1 struct{ NoOperandsInstruction }
type DUP2_X2 struct{ NoOperandsInstruction }
type F2D struct{ NoOperandsInstruction }
type F2I struct{ NoOperandsInstruction }
type F2L struct{ NoOperandsInstruction }
type FCMPG struct{ NoOperandsInstruction }
type FCMPL struct{ NoOperandsInstruction }
type FLOAD struct{ Index8Instruction }
type FLOAD_0 struct{ NoOperandsInstruction }
type FLOAD_1 struct{ NoOperandsInstruction }
type FLOAD_2 struct{ NoOperandsInstruction }
type FLOAD_3 struct{ NoOperandsInstruction }
type FSTORE struct{ Index8Instruction }
type FSTORE_0 struct{ NoOperandsInstruction }
type FSTORE_1 struct{ NoOperandsInstruction }
type FSTORE_2 struct{ NoOperandsInstruction }
type FSTORE_3 struct{ NoOperandsInstruction }
type AALOAD struct{ NoOperandsInstruction }
type BALOAD struct{ NoOperandsInstruction }
type CALOAD struct{ NoOperandsInstruction }
type DALOAD struct{ NoOperandsInstruction }
type FALOAD struct{ NoOperandsInstruction }
type IALOAD struct{ NoOperandsInstruction }
type LALOAD struct{ NoOperandsInstruction }
type SALOAD struct{ NoOperandsInstruction }
type I2B struct{ NoOperandsInstruction }
type I2C struct{ NoOperandsInstruction }
type I2S struct{ NoOperandsInstruction }
type I2L struct{ NoOperandsInstruction }
type I2F struct{ NoOperandsInstruction }
type I2D struct{ NoOperandsInstruction }
type L2D struct{ NoOperandsInstruction }
type L2F struct{ NoOperandsInstruction }
type L2I struct{ NoOperandsInstruction }
type LCMP struct{ NoOperandsInstruction }
type LDC struct{ Index8Instruction }
type LDC_W struct{ Index16Instruction }
type LDC2_W struct{ Index16Instruction }
type LLOAD struct{ Index8Instruction }
type LLOAD_0 struct{ NoOperandsInstruction }
type LLOAD_1 struct{ NoOperandsInstruction }
type LLOAD_2 struct{ NoOperandsInstruction }
type LLOAD_3 struct{ NoOperandsInstruction }
type LSTORE struct{ Index8Instruction }
type LSTORE_0 struct{ NoOperandsInstruction }
type LSTORE_1 struct{ NoOperandsInstruction }
type LSTORE_2 struct{ NoOperandsInstruction }
type LSTORE_3 struct{ NoOperandsInstruction }
type ILOAD struct{ Index8Instruction }
type ILOAD_0 struct{ NoOperandsInstruction }
type ILOAD_1 struct{ NoOperandsInstruction }
type ILOAD_2 struct{ NoOperandsInstruction }
type ILOAD_3 struct{ NoOperandsInstruction }
type ISTORE struct{ Index8Instruction }
type ISTORE_0 struct{ NoOperandsInstruction }
type ISTORE_1 struct{ NoOperandsInstruction }
type ISTORE_2 struct{ NoOperandsInstruction }
type ISTORE_3 struct{ NoOperandsInstruction }
type AASTORE struct{ NoOperandsInstruction }
type BASTORE struct{ NoOperandsInstruction }
type CASTORE struct{ NoOperandsInstruction }
type DASTORE struct{ NoOperandsInstruction }
type FASTORE struct{ NoOperandsInstruction }
type IASTORE struct{ NoOperandsInstruction }
type LASTORE struct{ NoOperandsInstruction }
type SASTORE struct{ NoOperandsInstruction }
type DMUL struct{ NoOperandsInstruction }
type FMUL struct{ NoOperandsInstruction }
type IMUL struct{ NoOperandsInstruction }
type LMUL struct{ NoOperandsInstruction }
type IF_ACMPEQ struct{ BranchInstruction }
type IF_ACMPNE struct{ BranchInstruction }
type IF_ICMPEQ struct{ BranchInstruction }
type IF_ICMPNE struct{ BranchInstruction }
type IF_ICMPLT struct{ BranchInstruction }
type IF_ICMPLE struct{ BranchInstruction }
type IF_ICMPGT struct{ BranchInstruction }
type IF_ICMPGE struct{ BranchInstruction }
type IFEQ struct{ BranchInstruction }
type IFNE struct{ BranchInstruction }
type IFLT struct{ BranchInstruction }
type IFLE struct{ BranchInstruction }
type IFGT struct{ BranchInstruction }
type IFGE struct{ BranchInstruction }
type IFNULL struct{ BranchInstruction }
type IFNONNULL struct{ BranchInstruction }
type DNEG struct{ NoOperandsInstruction }
type FNEG struct{ NoOperandsInstruction }
type INEG struct{ NoOperandsInstruction }
type LNEG struct{ NoOperandsInstruction }
type DREM struct{ NoOperandsInstruction }
type FREM struct{ NoOperandsInstruction }
type IREM struct{ NoOperandsInstruction }
type LREM struct{ NoOperandsInstruction }
type IOR struct{ NoOperandsInstruction }
type LOR struct{ NoOperandsInstruction }
type IXOR struct{ NoOperandsInstruction }
type LXOR struct{ NoOperandsInstruction }
type POP struct{ NoOperandsInstruction }
type POP2 struct{ NoOperandsInstruction }
type PUTFIELD struct{ Index16Instruction }
type PUTSTATIC struct{ Index16Instruction }
type RET struct{ Index8Instruction }
type RETURN struct{ NoOperandsInstruction }
type ARETURN struct{ NoOperandsInstruction }
type DRETURN struct{ NoOperandsInstruction }
type FRETURN struct{ NoOperandsInstruction }
type IRETURN struct{ NoOperandsInstruction }
type LRETURN struct{ NoOperandsInstruction }
type ISHL struct{ NoOperandsInstruction }
type ISHR struct{ NoOperandsInstruction }
type IUSHR struct{ NoOperandsInstruction }
type LSHL struct{ NoOperandsInstruction }
type LSHR struct{ NoOperandsInstruction }
type LUSHR struct{ NoOperandsInstruction }
type DSUB struct{ NoOperandsInstruction }
type FSUB struct{ NoOperandsInstruction }
type ISUB struct{ NoOperandsInstruction }
type LSUB struct{ NoOperandsInstruction }
type SWAP struct{ NoOperandsInstruction }
type NEW struct{ Index16Instruction }
type INSTANCEOF struct{ Index16Instruction }
type GET_FIELD struct{ Index16Instruction }
type GET_STATIC struct{ Index16Instruction }
type GOTO struct{ BranchInstruction }
type MONITORENTER struct{ NoOperandsInstruction }
type MONITOREXIT struct{ NoOperandsInstruction }
type NOP struct{ NoOperandsInstruction }
type INVOKENATIVE struct{ NoOperandsInstruction }
type JSR struct{ Index16Instruction }
